export enum ChainEnum {
  ETHEREUM = 'ETHEREUM',
  POLYGON = 'POLYGON',
  MUMBAI = 'MUMBAI',
  GOERLI = 'GOERLI',
  FILECOIN = 'FILECOIN',
  HYPERSPACE = 'HYPERSPACE',
  MANTLE_MAINET = 'MANTLE_MAINET',
  MANTLE_TESTNET = 'MANTLE_TESTNET',
}
