export enum ChainType {
  MUMBAI = 'MATIC_MUMBAI_RPC_URL',
  GOERLI = 'ETHEREUM_GOERLI_RPC_URL',
  ETHEREUM = 'ETHEREUM',
  POLYGON = 'POLYGON',
  MANTLE_MAINET = 'MANTLE_MAINET',
  MANTLE_TESTNET = 'MANTLE_TESTNET',
}
