export enum ActivityEnum {
    MINTED = 'Minted',
    LIST = 'List',
    CANCEL_LIST = 'Cancel List',
    PLACE_BID = 'Place Bid',
    UPDATE_BID = 'Update Bid',
    CANCEL_BID = 'Cancel Bid',
    AUCTION_WON = 'Won',
    AUCTION_LOST = 'Lost',
    TRANSFER = 'Transfer',
    SALE = 'Sale',
    UPDATE_OFFER = 'Update Offer',
    MAKE_OFFER = 'Make Offer',
    CANCEL_SALE = 'Cancel Sale',
    OFFER_ACCEPTED = 'Offer Accepted',
    CANCEL_OFFER = 'Cancel Offer',
    UPDATE_SALE = 'update sale',
    SALE_ENDED = 'sale ended',
    Create_Sale = 'create sale',
    Sale_Ended = 'sale ended'
}